// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjlehrnezceiamdpiwfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqbGVocm5lemNlaWFtZHBpd2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTAyOTYsImV4cCI6MjA2MjQ2NjI5Nn0.3FPTWprovqh51jXNz28ICXF-Sk-Z0KrGYV9CdSEcgCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);